# Generated by Django 4.1.1 on 2022-09-20 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigestIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Digest issue number.')),
                ('is_special', models.BooleanField(help_text='Is this digest issue special?')),
                ('status', models.CharField(choices=[('planning', 'planning'), ('gathering', 'gathering'), ('editing', 'editing'), ('published', 'published')], default='planning', max_length=16)),
                ('planned_at', models.DateField(help_text='Date this digest issue is planned to be published at.')),
                ('published_at', models.DateField(blank=True, help_text='Date this digest issue was actually published at.', null=True)),
            ],
            options={
                'verbose_name': 'digest issue',
                'verbose_name_plural': 'digest issues',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='DigestIssueLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('habr', 'Habr'), ('facebook', 'Facebook'), ('vk', 'Vk')], default='habr', max_length=16)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'digest link',
                'verbose_name_plural': 'digest links',
                'ordering': ['-issue__number', 'type'],
            },
        ),
        migrations.CreateModel(
            name='GatheringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_count', models.IntegerField(default=0)),
                ('saved_count', models.IntegerField(default=0)),
                ('filtered_count', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-finished_at', 'source__title'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(blank=True, max_length=256, null=True)),
                ('url', models.URLField()),
                ('origin', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('article', 'article'), ('news', 'news'), ('release', 'release'), ('video', 'video'), ('other', 'other'), ('unknown', 'unknown')], default='unknown', max_length=8)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=2)),
                ('published_at', models.DateTimeField()),
                ('gathered_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'ordering': ['-gathered_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=32, unique=True)),
                ('url', models.URLField(unique=True)),
                ('type', models.CharField(choices=[('rss', 'RSS'), ('html', 'HTML'), ('youtube', 'YouTube')], default='rss', max_length=8)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=2)),
            ],
            options={
                'verbose_name': 'source',
                'verbose_name_plural': 'sources',
                'ordering': ['enabled', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['title'], name='gatherer_so_title_aab62d_idx'),
        ),
        migrations.AddField(
            model_name='news',
            name='gathering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gatherer.gatheringresult'),
        ),
        migrations.AddField(
            model_name='gatheringresult',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gatherer.source'),
        ),
        migrations.AddField(
            model_name='digestissuelink',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatherer.digestissue'),
        ),
        migrations.AddIndex(
            model_name='digestissue',
            index=models.Index(fields=['number'], name='gatherer_di_number_92ac2e_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['title'], name='gatherer_ne_title_bf8188_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['url'], name='gatherer_ne_url_58d142_idx'),
        ),
    ]
